DROP TABLE IF EXISTS wcf1_sfs_log;
CREATE TABLE wcf1_sfs_log (
	logID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	userID INT(10),
	username VARCHAR(255) NOT NULL DEFAULT '',
	ipAddress VARCHAR(39) NOT NULL DEFAULT '',
	email VARCHAR(255) NOT NULL DEFAULT '',
	logDate INT(10) NOT NULL DEFAULT 0,
	eventClassName VARCHAR(80) NOT NULL DEFAULT '',
	eventName VARCHAR(50) NOT NULL DEFAULT '',
	status TINYINT(1) NOT NULL DEFAULT 0,
	error TEXT
);
